version: "2"

linters:
  default: none

  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - gocritic
    - gocyclo
    - gomoddirectives
    - govet
    - ineffassign
    - misspell
    - modernize
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    revive:
      # see: https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,*testing.B,*testing.F'
        - name: duplicated-imports
        - name: early-return
        - name: error-naming
        - name: errorf
        - name: package-comments
          disabled: true
        - name: time-equal
        - name: unnecessary-stmt
        - name: use-any
        - name: useless-break
        - name: var-declaration
        - name: var-naming
          arguments: [ [ ],[ ],[ skipPackageNameChecks: true ] ]
        - name: waitgroup-by-value
      toolchain-forbidden: true
      go-version-pattern: '^1\.25\.0$'
    nolintlint:
      require-specific: true
    staticcheck:
      checks:
        - all
        - '-QF1012' # https://staticcheck.dev/docs/checks#QF1012
        - '-ST1000' # https://staticcheck.dev/docs/checks#ST1000
        - '-ST1020' # https://staticcheck.dev/docs/checks#ST1020
        - '-ST1021' # https://staticcheck.dev/docs/checks#ST1021
        - '-ST1022' # https://staticcheck.dev/docs/checks#ST1022
  exclusions:
    paths:
      - .gocache

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
      module-path: github.com/flc1125/go-gitlab-webhook/v3