codecov:
  require_ci_to_pass: true

fixes:
  - "github.com/flc1125/go-gitlab-webhook/v3/::"
  - "github.com/flc1125/go-gitlab-webhook/middleware/otel/v3/::middleware/otel/"

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 50%

    patch:
      default:
        target: 90%
        threshold: 80%
