name: Go Lint

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches:
      - 3.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: Tools cache
        uses: actions/cache@v5
        env:
          cache-name: go-tools-cache
        with:
          path: .tools
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./internal/tools/**') }}

      - name: Run lint
        run: make lint

      - name: Build
        run: make build

      - name: Check clean repository
        run: make check-clean-work-tree